services:
  vue_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ".:/usr/src/vue_app"
    ports:
      - "5173:5173"
    env_file: ".env"
